### ISSUE TITLE
mongoose schema 옵션 추가

### ISSUE THREAD

**Issue by hotsoycandy** [fred16157/manager-server#4]
https://mongoosejs.com/docs/guide.html#timestamps
mongoose schema timestamp 관련 옵션입니다. 참고해보세요

**Comment by fred16157** [comment]
https://github.com/fred16157/manager-server/commit/0944a2fe0a2caba5ce8b9661bb937e841ebb9d63 https://github.com/fred16157/manager-server/commit/780bd53928ef33336d60ff8a3d7fd53cc350d10c Book, Log, Ticket, User 스키마에 timestamp 옵션을 추가했습니다.
