### ISSUE TITLE
validation 필요

### ISSUE THREAD

**Issue by hotsoycandy** [fred16157/manager-server#5]
API에서도 DB에서도 validation이 되어있지 않습니다. 어떤값이든 허용하는 것은 서버운영에 위험합니다. validation 과정을 추가하는 것을 고려해보세요.

**Comment by fred16157** [comment]
https://github.com/fred16157/manager-server/commit/35e4ad9e1e9cf5d382a89b0a640986ae78a5e757 https://github.com/fred16157/manager-server/commit/780bd53928ef33336d60ff8a3d7fd53cc350d10c 서버 운영에 민감한 요청에 검사 과정을 추가했습니다.
