### ISSUE TITLE
password entrypt 필요

### ISSUE THREAD

**Issue by hotsoycandy** [fred16157/manager-server#6]
암호는 DB에 저장될 때 암호화 되어서 저장되어야 합니다. 수정이 필요해 보입니다.

**Comment by fred16157** [comment]
https://github.com/fred16157/manager-server/commit/35e4ad9e1e9cf5d382a89b0a640986ae78a5e757 스키마에 getter setter를 부여하여 암호화 과정을 추가하였습니다.
